config/routes.rb
GlobalStories::Application.routes.draw do
  devise_for :users

  resources :chapters
  resources :stories
 
  root :to => 'stories#init'
  post 'stories/chapter'

  resources :stories do
    resources :chapters, :only => [:new, :create, :index, :edit, :show, :destroy]
  end

  devise_for :users do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  resources :stories do
    get :favorite, on: :member
  end

end

app/models/chapter.rb
class Chapter < ActiveRecord::Base
  attr_accessible :created_by, :creation_date, :image, :main_chapter, :story_id, :subtitle
  mount_uploader :image, ChapterImagesUploader
  belongs_to :story
  belongs_to :user
end

app/models/favorite_story.rb
class FavoriteStory < ActiveRecord::Base
  attr_accessible :integer, :story_id, :user_id
  belongs_to :story
  belongs_to :user
end

app/models/story.rb
class Story < ActiveRecord::Base
  attr_accessible :created_by, :creation_date, :genre, :intro, :main_story, :number_of_writers, :title
  has_many :chapters
  belongs_to :user

  has_many :favorite_stories 
  has_many :favorited_by, through: :favorite_stories, source: :user 

  def main_story
    chapters.pluck(:main_chapter).join('<br/>').html_safe
    #content_tag(:b, chapters.pluck(:main_chapter).join("\n").html_safe )
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body

  has_many :stories
  has_many :chapters

  has_many :favorite_stories 
  has_many :favorites, through: :favorite_stories
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/chapters_controller.rb
class ChaptersController < ApplicationController
  # GET /chapters
  # GET /chapters.json


  def index
    @story = Story.find params[:story_id]

      @chapters = Chapter.all
    
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @chapters }
    end
  end


  # GET /chapters/1
  # GET /chapters/1.json
  def show
    @chapter = Chapter.find(params[:id])
    
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @chapter }
    end
  end

  # GET /chapters/new
  # GET /chapters/new.json
  def new
    @story = Story.find params[:story_id]
    @chapter = Chapter.new
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @chapter }
    end
  end

  # PUT /chapters/1
  # PUT /chapters/1.json
   def update
     
    @story = Story.find params[:story_id]
    @chapter = Chapter.new params[:chapter]
    @chapter.story = @story
    
     respond_to do |format|
       if @chapter.update_attributes(params[:chapter])
         format.html { redirect_to @chapter, notice: 'Chapter was successfully updated.' }
         format.json { head :no_content }
       else
         format.html { render action: "edit" }
         format.json { render json: @chapter.errors, status: :unprocessable_entity }
       end
     end
   end

  # GET /chapters/1/edit
  def edit
    @chapter = Chapter.find(params[:id])
    @story = Story.find params[:story_id]
  end

  # POST /chapters
  # POST /chapters.json
  def create
    @story = Story.find params[:story_id]
    @chapter = Chapter.new(params[:chapter])
    @chapter.story = @story
    @chapter.user = current_user
    respond_to do |format|
      if @chapter.save
        format.html { redirect_to @chapter, notice: 'Chapter was successfully created.' }
        format.json { render json: @chapter, status: :created, location: @chapter }
      else
        format.html { render action: "new" }
        format.json { render json: @chapter.errors, status: :unprocessable_entity }
      end
    end
  end

  

  # DELETE /chapters/1
  # DELETE /chapters/1.json
  def destroy
    @chapter = Chapter.find(params[:id])
    @chapter.destroy

    respond_to do |format|
      format.html { redirect_to chapters_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
  # GET /stories
  # GET /stories.json
  def index
    @stories = Story.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @stories }
    end
  end

  # GET /stories/1
  # GET /stories/1.json
  def show
    @story = Story.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @story }
    end
  end

  # GET /stories/new
  # GET /stories/new.json
  def new
    @story = Story.new
    @story.user = current_user
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @story }
    end
  end

  # GET /stories/1/edit
  def edit
    @story = Story.find(params[:id])
  end

  # POST /stories
  # POST /stories.json
  def create
    @story = Story.new(params[:story])
    @story.user = current_user
    respond_to do |format|
      if @story.save
        format.html { redirect_to @story, notice: 'Story was successfully created.' }
        format.json { render json: @story, status: :created, location: @story }
      else
        format.html { render action: "new" }
        format.json { render json: @story.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /stories/1
  # PUT /stories/1.json
  def update
    @story = Story.find(params[:id])

    respond_to do |format|
      if @story.update_attributes(params[:story])
        format.html { redirect_to @story, notice: 'Story was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @story.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stories/1
  # DELETE /stories/1.json
  def destroy
    @story = Story.find(params[:id])
    @story.destroy

    respond_to do |format|
      format.html { redirect_to stories_url }
      format.json { head :no_content }
    end
  end

  def chapter
   Story.find(params[:id]).chapter.create(params[:chapter])
   flash[:notice] = "Your chapter has been added !!!"
   redirect_to :action => "show", :id => params[:id]
  end
  

  # Add and remove favorite recipes
  # for current_user
  def favorite
    type = params[:type]
    if type == "favorite"
      current_user.favorites << @story
      redirect_to @story, notice: 'You favorited #{@story.title}'

    elsif type == "unfavorite"
      current_user.favorites.delete(@story)
      redirect_to @story, notice: 'Unfavorited #{@story.title}'

    else
      # Type missing, nothing happens
      redirect_to @story, notice: 'Nothing happened.'
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chapters_helper.rb
module ChaptersHelper
end

app/helpers/stories_helper.rb
module StoriesHelper
end

app/views/chapters/_form.html.erb
<%= form_for([@story,@chapter]) do |f| %>
  <% if @chapter.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@chapter.errors.count, "error") %> prohibited this chapter from being saved:</h2>

      <ul>
      <% @chapter.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <p>
    <b>Story:</b>
    <%= @story.id %>
  </p>
   <p>
    <b>Story's Title:</b>
    <%= @story.title %>
  </p>
  <div class="field">
    <%= f.label :subtitle %><br />
    <%= f.text_field :subtitle %>
  </div>
  <div class="field">
    <%= f.label :main_chapter %><br />
    <%= f.text_area :main_chapter %>
  </div>
 <div class="field">
    <%= f.label :image %><br />
    <%= f.file_field :image %>
  </div>
  <div class="field">
    <%= f.label :creation_date %><br />
    <%= f.datetime_select :creation_date %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/chapters/edit.html.erb
<h1>Editing chapter</h1>

<%= render 'form' %>

<%= link_to 'Show', @chapter %> |
<%= link_to 'Back', chapters_path %>

app/views/chapters/index.html.erb
<h3>Written Chapters</h3>
<table>
  <tr>
    <th>Subtitle</th>
    <th>Main chapter</th>
    <th>Story</th>
    <th>Created by</th>
    <th>Creation date</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
<% @chapters.each do |chapter| %>
  <tr>
    <% if chapter.story_id == @story.id %>
        <td><%= chapter.subtitle %></td>
        <td><%= chapter.main_chapter %></td>
        <td><%= chapter.story_id %></td>
        <td><%= chapter.user_id %></td>
        <td><%= chapter.creation_date %></td>
        <td><%= link_to 'Show', story_chapter_path(@story,chapter) %></td>
        <% if user_signed_in? %>
            <td><%= link_to 'Edit', edit_story_chapter_path(@story,chapter) %></td>
            <td><%= link_to 'Destroy', chapter, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
    <%end %>
  </tr>
<% end %>
</table>

<br />
<% if user_signed_in? %>
    <%= link_to 'New Chapter', new_story_chapter_path(@story) %>
<% end %>

app/views/chapters/new.html.erb
<h1>New chapter</h1>

<%= render 'form' %>

<%= link_to 'Back', stories_path %>

app/views/chapters/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Story:</b>
  <%= @chapter.story_id %>
</p>
<p>
  <b>Subtitle:</b>
  <%= @chapter.subtitle %>
</p>

<p>
  <b>Main chapter:</b>
  <%= @chapter.main_chapter %>
</p>
<p>
  <%= image_tag @chapter.image,:size => '300x200' %>
</p>

<p>
  <b>Creation date:</b>
  <%= @chapter.creation_date %>
</p>


<!-- link_to 'Edit', edit_story_chapter_path(@chapter,@story) -->
<%= link_to 'Back', stories_path(@story) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
	  <meta charset="utf-8">
	    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
	    <meta name="viewport" content="width=device-width, initial-scale=1.0">
	    <title><%= content_for?(:title) ? yield(:title) : "Global Stories" %></title>
	    <%= csrf_meta_tags %>
		<%= stylesheet_link_tag "application", :media => "all" %>
	    <%= javascript_include_tag :defaults %>
	</head>
	<body>
		<div class="navbar navbar-fixed-top">
	      <div class="navbar-inner">
	        <div class="container">
	          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
	            <span class="icon-bar"></span>
	            <span class="icon-bar"></span>
	            <span class="icon-bar"></span>
	          </a>
	          <%= link_to "Global Stories", root_path, :class => "brand"%>
				<div class="container nav-collapse">
		            <ul class="nav pull-right">
		              <% if user_signed_in? %>
	      	 				  <%= link_to current_user.email %>
	      	 				</br>
		              
	                  <%= link_to('Logout', destroy_user_session_path, :method => 'delete')%>

		              <% else %>
		                <%= link_to('Sign up', new_user_registration_path) %>
		                </br>
		                <%= link_to('Login', new_user_session_path) %>
		              <% end %>
		            </ul>
		        </div><!--/.nav-collapse -->
	        </div>
	      </div>
	    </div>
		<div class="container">
	    	<div class="content">
				<% if flash[:notice]%>
	    			<div class="alert alert-success">
	      				<%= flash[:notice]%>
	    			</div>
	  			<% end %>
	  			<% if flash[:alert]%>
	    			<div class="alert alert-error">
	      				<% flash[:alert]%>
	      			</div>
				<% end %> 
	        	<div class="row">
	           		<div class="span12">
	           			<%= link_to 'Home', root_path %>
	           			<br/>
	           			<%= link_to 'Stories', stories_path %>
	           			<br/>

	           			<%= yield %>
	            	</div>
	       		</div><!--/row-->
	    	</div><!--/content-->

		    <footer>
		    	<br/>
		    	<p>&copy; Victor Lloret 2012</p>
		    </footer>
		</div> <!-- /container -->
	</body>
</html>

app/views/stories/_form.html.erb
<%= form_for(@story) do |f| %>
  <% if @story.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@story.errors.count, "error") %> prohibited this story from being saved:</h2>

      <ul>
      <% @story.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :intro %><br />
    <%= f.text_area :intro %>
  </div>
  <div class="field">
    <%= f.label :genre %><br />
    <%= f.text_field :genre %>
  </div>
  <div class="field">
    <%= f.label :number_of_writers %><br />
    <%= f.number_field :number_of_writers %>
  </div>
  <div class="field">
    <%= f.label :creation_date %><br />
    <%= f.datetime_select :creation_date %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/stories/edit.html.erb
<h1>Editing story</h1>

<%= render 'form' %>

<%= link_to 'Show', @story %> |
<%= link_to 'Back', stories_path %>

app/views/stories/index.html.erb
<h3>Stories</h3>

<table>
  <tr>
    <th>Title</th>
    <th>Intro</th>
    <th>Genre</th>
    <th>Writers</th>
    <th>Created by</th>
    <th>Creation date</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @stories.each do |story| %>
  <tr>
    <td><%= story.title %></td>
    <td><%= story.intro %></td>
    <td><%= story.genre %></td>
    <td><%= story.number_of_writers %></td>
    <td><%= story.user_id %></td>
    <td><%= story.creation_date %></td>
    <td><%= link_to 'Show', story %></td>
    <% if user_signed_in? %>
        <td><%= link_to 'Edit', edit_story_path(story) %></td>
        <td><%= link_to 'Destroy', story, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    <% end %>
  </tr>
<% end %>
</table>

<br />
<%= link_to 'New Story', new_story_path %>

app/views/stories/init.html.erb
<h1>Global Stories</h1>

<div class="container">
    <div class="span12">
        <p>Welcome to Global Stories. Here you'll have the chance to be a writer. Don't you ever planned to write a book?? Here you have your first oportunity to collaborate in one story (or more). Just start a story or follow a started one.
        	Enjoy your inspiration.
        </p>
        <br/>
    </div>
    <%= link_to 'Start your Trip', stories_path %>
</div><!--/row-->

<br />

app/views/stories/new.html.erb
<h1>New story</h1>

<%= render 'form' %>

<%= link_to 'Back', stories_path %>

app/views/stories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @story.title %>
</p>

<p>
  <b>Intro:</b>
  <%= @story.intro %>
</p>

<p>
  <b>Genre:</b>
  <%= @story.genre %>
</p>

<p>
  <b>Number of writers:</b>
  <%= @story.number_of_writers %>
</p>

<p>
  <b>Creation date:</b>
  <%= @story.creation_date %>
</p>


<b>Main story</b>
<br/>
    <%= @story.main_story %>
</br>
</br>
<% if user_signed_in? %>
  <% #link_to "favorite",   favorite_story_path(@recipe, type: "favorite"), method: "get" %>
  <% #link_to "unfavorite", favorite_story_path(@recipe, type: "unfavorite"), method: "get" %>
  
  <b>Do you want to collab? write a new chapter</b>
  <br/>
  <%= link_to 'New Chapter', new_story_chapter_path(@story) %>
  <br/>
  </br>
<% end %>
<b>Take a look at the done chapters</b>
<br/>
<%= link_to 'Chapters', story_chapters_path(@story) %>
<br/>
</br>
<% if user_signed_in? %>
  <%= link_to 'Edit', edit_story_path(@story) %> |
  <%= link_to 'Back', stories_path %>
<% end %>